name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python Virtual Env
        run: pip3 install virtualenv

      - name: Virtual Env
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-venv-

      - name: Activate Virtual Env
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt

      - name: Create archive of dependencies
        run: cd ./venv/lib/python3.11/site-packages; zip -r9 ../../../../fastapi.zip .
      
      - name: Add API files to zip
        run: cd ./items_api
      
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: fastapi
          path: fastapi.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with: 
          version: 1
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Download Lambda fastapi.zip
        uses: actions/download-artifact@v2
        with: 
          name: fastapi
      
      - name: Upload to S3 bucket
        run: aws s3 cp fastapi.zip s3://fastapi-test-bucket-larisa/fastapi.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Deply new Lambda
        run:  aws lambda update-function-code --function-name FastAPI --s3-bucket fastapi-test-bucket-larisa --s3-key fastapi.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
